apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ejcx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ejcx
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ejcx
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ejcx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ejcx
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ierr-tenant/rhtap-demo-app/hacbs-test-project-ejcx@sha256:6633df96a13357cac8e426998d49dab1e7fd16badcc51505c5e13de3daaa8353
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
